name: "Setup Docker"
description: "Setup Docker environment for docker/build-push-action and login with DockerHub"

inputs:
  registry_username:
    description: "Username for image registry"
    required: true
  registry_password:
    description: "Password for image registry"
    required: true
  dockerfile:
    description: "Dockerfile to build"
    required: true
  build_args:
    description: "Build args for Dockerfile"
    required: true
  tags:
    description: "Tags for Docker image"
    required: true
  # base_image:
  #   description: "Base image for build"
  #   required: false
  #   default: ""
  # base_image_jumanpp:
  #   description: "Juman++ base image for build"
  #   required: false
  #   default: ""
  # kwja_version:
  #   description: "Version of KWJA"
  #   required: false
  #   default: ""

runs:
  using: "composite"
  steps:
    - uses: docker/setup-qemu-action@v3

    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      with:
        username: ${{inputs.registry_username}}
        password: ${{inputs.registry_password}}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        platforms: linux/amd64,linux/arm64
        build-args: ${{ inputs.build_args }}
        push: true
        tags: ${{ inputs.tags }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
