name: "Setup Docker"
description: "Setup Docker environment for docker/build-push-action and login with DockerHub"

inputs:
  registry_username:
    description: “Username for image registry”
    required: true
  registry_password:
    description: “Password for image registry”
    required: true

runs:
  using: "composite"
  steps:
    - uses: docker/setup-qemu-action@v3

    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      with:
        username: ${{inputs.registry_username}}
        password: ${{inputs.registry_password}}
