name: "Setup Docker"
description: "Setup Docker environment for docker/build-push-action and login with DockerHub"

runs:
  using: "composite"
  steps:
    - uses: docker/setup-qemu-action@v3

    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
