name: build-push-jumanpp-knp

on:
  schedule:
    - cron: '0 20 * * 1'  # run at 5:00 every week (JST)
  workflow_dispatch:

env:
  registry-user: kunlp

jobs:
  build-builder:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        base-image: ["ubuntu:18.04", "ubuntu:20.04"]  # Juman++ cannot be built on ubuntu:22.04
        target: ["jumanpp", "knp"]
        include:
          - base-image: "ubuntu:18.04"
            tag: "ubuntu18.04-builder"
          - base-image: "ubuntu:20.04"
            tag: "ubuntu20.04-builder"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.target }}.dockerfile
          platforms: linux/amd64  # or linux/amd64,linux/arm64
          build-args: BASE_IMAGE=${{ matrix.base-image }}
          push: false
          load: true
          tags: ${{ env.registry-user }}/${{ matrix.target }}:${{ matrix.tag }}
          target: builder
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  build-push:
    needs: build-builder
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        base-image: ["ubuntu:18.04", "ubuntu:20.04"]  # Juman++ cannot be build on ubuntu:22.04
        target: ["jumanpp", "knp"]
        include:
          - base-image: "ubuntu:18.04"
            tag: "ubuntu18.04"
          - base-image: "ubuntu:20.04"
            tag: "ubuntu20.04"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Generate tags
        id: generate-tags
        # jumanpp:latest is excluded because there is another alpine-based image
        run: |
          tag_prefix="${{ env.registry-user }}/${{ matrix.target }}"
          tags="${tag_prefix}:${{ matrix.tag }}"
          if [[ ${{ matrix.base-image }} == 'ubuntu:20.04' ]]; then \
            tags+=",${tag_prefix}:ubuntu" \
            if [[ ${{ matrix.target }} != 'jumanpp' ]]; then \
              tags+=",${tag_prefix}:latest" \
            fi \
          fi
          echo "::set-output name=tags::${tags}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.target }}.dockerfile
          platforms: linux/amd64  # or linux/amd64,linux/arm64
          build-args: BASE_IMAGE=${{ matrix.base-image }}
          push: true
          tags: ${{ steps.generate-tags.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  build-push-jumanpp-knp:
    needs: build-push
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        base-image: ["ubuntu:18.04", "ubuntu:20.04"]  # Juman++ cannot be build on ubuntu:22.04
        include:
          - base-image: "ubuntu:18.04"
            tag: "ubuntu18.04"
          - base-image: "ubuntu:20.04"
            tag: "ubuntu20.04"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Generate tags
        id: generate-tags
        run: |
          tag_prefix="${{ env.registry-user }}/jumanpp-knp"
          tags="${tag_prefix}:${{ matrix.tag }}"
          [[ ${{ matrix.base-image }} == 'ubuntu:20.04' ]] && tags+=",${tag_prefix}:ubuntu,${tag_prefix}:latest"
          echo "::set-output name=tags::${tags}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: jumanpp-knp.dockerfile
          platforms: linux/amd64  # or linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE_JUMANPP=${{ env.registry-user }}/jumanpp:${{ matrix.tag }}
            BASE_IMAGE_KNP=${{ env.registry-user }}/knp:${{ matrix.tag }}
          push: true
          tags: ${{ steps.generate-tags.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
