name: build-push-jumanpp

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 20 * * 1'  # run at 5:00 every week (JST)
  workflow_dispatch:

jobs:
  builder:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        base-image: ["ubuntu:18.04", "ubuntu:20.04"]  # Juman++ cannot be built on ubuntu:22.04
        include:
          - base-image: "ubuntu:18.04"
            tag: "ubuntu18.04"
          - base-image: "ubuntu:20.04"
            tag: "ubuntu20.04"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      # - uses: actions/cache@v3
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ github.ref }}-${{ github.sha }}
      #     restore-keys: |
      #       ${{ github.ref }}-${{ github.sha }}
      #       ${{ github.ref }}
      #       refs/head/main

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: jumanpp.dockerfile
          platforms: linux/amd64  # or linux/amd64,linux/arm64
          build-args: BASE_IMAGE=${{ matrix.base-image }}
          push: false
          tags: nobug5c9/jumanpp:${{ matrix.tag }}-builder
          target: builder
          cache-from: nobug5c9/knp:${{ matrix.tag }}-builder
          cache-to: nobug5c9/knp:${{ matrix.tag }}-builder

      # - name: Move cache
      #   run: |
      #     rm -rf /tmp/.buildx-cache
      #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build-push:
    needs: builder
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        base-image: ["ubuntu:18.04", "ubuntu:20.04"]  # Juman++ cannot be build on ubuntu:22.04
        include:
          - base-image: "ubuntu:18.04"
            tag: "ubuntu18.04"
          - base-image: "ubuntu:20.04"
            tag: "ubuntu20.04"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      # - uses: actions/cache@v3
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ github.ref }}-${{ github.sha }}
      #     restore-keys: |
      #       ${{ github.ref }}-${{ github.sha }}
      #       ${{ github.ref }}
      #       refs/head/main

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: jumanpp.dockerfile
          platforms: linux/amd64  # or linux/amd64,linux/arm64
          build-args: BASE_IMAGE=${{ matrix.base-image }}
          push: true
          tags: nobug5c9/jumanpp:${{ matrix.tag }}
          # target: builder
          # cache-from: type=local,src=/tmp/.buildx-cache
